src/main/java/com/ubuniworks/model/User.java
package com.ubuniworks.model;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.search.annotations.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import java.io.Serializable;
import java.util.*;

/**
 * This class represents the basic "user" object in AppFuse that allows for authentication
 * and user management.  It implements Spring Security's UserDetails interface.
 *
 * @author <a href="mailto:matt@raibledesigns.com">Matt Raible</a>
 *         Updated by Dan Kibler (dan@getrolling.com)
 *         Extended to implement Spring UserDetails interface
 *         by David Carter david@carter.net
 */
@Entity
@Table(name = "app_user")
@Indexed
@XmlRootElement
public class User extends BaseObject implements Serializable, UserDetails {
    private static final long serialVersionUID = 3832626162173359411L;

    private Long id;
    private String username;                    // required
    private String password;                    // required
    private String confirmPassword;
    private String passwordHint;
    private String firstName;                   // required
    private String lastName;                    // required
    private String email;                       // required; unique
    private String phoneNumber;
    private String website;
    private Address address = new Address();
    private Integer version;
    private Set<com.ubuniworks.model.Role> roles = new HashSet<com.ubuniworks.model.Role>();
    private boolean enabled;
    private boolean accountExpired;
    private boolean accountLocked;
    private boolean credentialsExpired;
    private Set<com.ubuniworks.model.Idea> ideas;
    private Set<com.ubuniworks.model.Idea> likedIdeas;
    private Set<com.ubuniworks.model.Pastproject> pastprojects = new HashSet<com.ubuniworks.model.Pastproject>(0);
    private Set<com.ubuniworks.model.Experience> experiences = new HashSet<com.ubuniworks.model.Experience>(0);
    private String profilepic;
    private String aboutme;

    /**
     * Default constructor - creates a new instance with no values set.
     */
    public User() {
    }

    /**
     * Create a new instance and set the username.
     *
     * @param username login name for user.
     */
    public User(final String username) {
        this.username = username;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @DocumentId
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(nullable = false, length = 50, unique = true)
    @Field
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(nullable = false)
    @XmlTransient
    @JsonIgnore
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Transient
    @XmlTransient
    @JsonIgnore
    public String getConfirmPassword() {
        return confirmPassword;
    }

    public void setConfirmPassword(String confirmPassword) {
        this.confirmPassword = confirmPassword;
    }

    @Column(name = "password_hint")
    @XmlTransient
    public String getPasswordHint() {
        return passwordHint;
    }

    public void setPasswordHint(String passwordHint) {
        this.passwordHint = passwordHint;
    }

    @Column(name = "first_name", nullable = false, length = 50)
    @Field
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "last_name", nullable = false, length = 50)
    @Field
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(nullable = false, unique = true)
    @Field
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "phone_number")
    @Field(analyze = Analyze.NO)
    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Field
    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * Returns the full name.
     *
     * @return firstName + ' ' + lastName
     */
    @Transient
    public String getFullName() {
        return firstName + ' ' + lastName;
    }

    @Embedded
    @IndexedEmbedded
    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @Fetch(FetchMode.SELECT)
    @JoinTable(
            name = "user_role",
            joinColumns = {@JoinColumn(name = "user_id")},
            inverseJoinColumns = @JoinColumn(name = "role_id")
    )
    public Set<com.ubuniworks.model.Role> getRoles() {
        return roles;
    }

    public void setRoles(Set<com.ubuniworks.model.Role> roles) {
        this.roles = roles;
    }

    /**
     * Convert user roles to LabelValue objects for convenience.
     *
     * @return a list of LabelValue objects with role information
     */
    @Transient
    public List<LabelValue> getRoleList() {
        List<LabelValue> userRoles = new ArrayList<LabelValue>();

        if (this.roles != null) {
            for (com.ubuniworks.model.Role role : roles) {
                // convert the user's roles to LabelValue Objects
                userRoles.add(new LabelValue(role.getName(), role.getName()));
            }
        }

        return userRoles;
    }

    /**
     * Adds a role for the user
     *
     * @param role the fully instantiated role
     */
    public void addRole(com.ubuniworks.model.Role role) {
        getRoles().add(role);
    }

    /**
     * @return GrantedAuthority[] an array of roles.
     * @see org.springframework.security.core.userdetails.UserDetails#getAuthorities()
     */
    @Transient
    @JsonIgnore // needed for UserApiITest in appfuse-ws archetype
    public Set<GrantedAuthority> getAuthorities() {
        Set<GrantedAuthority> authorities = new LinkedHashSet<>();
        authorities.addAll(roles);
        return authorities;
    }

    @Version
    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "account_enabled")
    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    @Column(name = "account_expired", nullable = false)
    public boolean isAccountExpired() {
        return accountExpired;
    }

    public void setAccountExpired(boolean accountExpired) {
        this.accountExpired = accountExpired;
    }

    /**
     * @return true if account is still active
     * @see org.springframework.security.core.userdetails.UserDetails#isAccountNonExpired()
     */
    @Transient
    public boolean isAccountNonExpired() {
        return !isAccountExpired();
    }

    @Column(name = "account_locked", nullable = false)
    public boolean isAccountLocked() {
        return accountLocked;
    }

    public void setAccountLocked(boolean accountLocked) {
        this.accountLocked = accountLocked;
    }

    /**
     * @return false if account is locked
     * @see org.springframework.security.core.userdetails.UserDetails#isAccountNonLocked()
     */
    @Transient
    public boolean isAccountNonLocked() {
        return !isAccountLocked();
    }

    @Column(name = "credentials_expired", nullable = false)
    public boolean isCredentialsExpired() {
        return credentialsExpired;
    }

    public void setCredentialsExpired(boolean credentialsExpired) {
        this.credentialsExpired = credentialsExpired;
    }

    /**
     * @return true if credentials haven't expired
     * @see org.springframework.security.core.userdetails.UserDetails#isCredentialsNonExpired()
     */
    @Transient
    public boolean isCredentialsNonExpired() {
        return !credentialsExpired;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<com.ubuniworks.model.Idea> getIdeas() {
        return this.ideas;
    }

    public void setIdeas(Set<com.ubuniworks.model.Idea> ideas_1) {
        this.ideas = ideas_1;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "likers")
    public Set<com.ubuniworks.model.Idea> getLikedIdeas() {
        return this.likedIdeas;
    }

    public void setLikedIdeas(Set<Idea> ideas) {
        this.likedIdeas = ideas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<com.ubuniworks.model.Pastproject> getPastprojects() {
        return pastprojects;
    }

    public void setPastprojects(Set<Pastproject> pastprojects) {
        this.pastprojects = pastprojects;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<com.ubuniworks.model.Experience> getExperiences() {
        return experiences;
    }

    public void setExperiences(Set<com.ubuniworks.model.Experience> experiences) {
        this.experiences = experiences;
    }


    @Column(name = "aboutme")
    public String getAboutme() {
        return this.aboutme;
    }

    public void setAboutme(String aboutme) {

src/main/java/com/ubuniworks/webapp/controller/ActivitiesController.java
package com.ubuniworks.webapp.controller;

import com.ubuniworks.dao.SearchException;
import com.ubuniworks.service.GenericManager;
import com.ubuniworks.model.Activities;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ExtendedModelMap;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping("/activitiess*")
public class ActivitiesController {
    private GenericManager<Activities, Integer> activitiesManager;

    @Autowired
    public void setActivitiesManager(@Qualifier("activitiesManager") GenericManager<Activities, Integer> activitiesManager) {
        this.activitiesManager = activitiesManager;
    }

    @RequestMapping(method = RequestMethod.GET)
    public Model handleRequest(@RequestParam(required = false, value = "q") String query)
    throws Exception {
        Model model = new ExtendedModelMap();
        try {
            model.addAttribute(activitiesManager.search(query, Activities.class));
        } catch (SearchException se) {
            model.addAttribute("searchError", se.getMessage());
            model.addAttribute(activitiesManager.getAll());
        }
        return model;
    }
}

src/main/java/com/ubuniworks/webapp/controller/ActivitiesFormController.java
package com.ubuniworks.webapp.controller;

import com.ubuniworks.model.Activities;
import com.ubuniworks.service.GenericManager;
import com.ubuniworks.service.IdeaManager;
import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.Locale;

@Controller
@RequestMapping("/activitiesform*")
public class ActivitiesFormController extends BaseFormController {
    private GenericManager<Activities, Integer> activitiesManager = null;
    private IdeaManager ideaManager = null;

    @Autowired
    public void setActivitiesManager(@Qualifier("activitiesManager") GenericManager<Activities, Integer> activitiesManager) {
        this.activitiesManager = activitiesManager;
    }

    public ActivitiesFormController() {
        setCancelView("redirect:ideas");
        setSuccessView("redirect:ideas");
    }

    @Autowired
    public void setIdeaManager(IdeaManager ideaManager) {
        this.ideaManager = ideaManager;
    }

    @ModelAttribute
    @RequestMapping(method = RequestMethod.GET)
    protected Activities showForm(HttpServletRequest request)
            throws Exception {
        String idactivities = request.getParameter("idactivities");
        String ididea = request.getParameter("ididea");

        Activities activity = new Activities();
        if (!StringUtils.isBlank(idactivities)) {
            activity = activitiesManager.get(new Integer(idactivities));
        } else if (!StringUtils.isBlank(ididea)) {
            activity.setIdea(ideaManager.get(Integer.valueOf(ididea)));
        }

        return activity;
    }

    @RequestMapping(method = RequestMethod.POST)
    public String onSubmit(Activities activities, BindingResult errors, HttpServletRequest request,
                           HttpServletResponse response)
            throws Exception {
        if (request.getParameter("cancel") != null) {
            return getCancelView();
        }

        if (validator != null) { // validator is null during testing
            validator.validate(activities, errors);

            if (errors.hasErrors() && request.getParameter("delete") == null) { // don't validate when deleting
                return "activitiesform";
            }
        }

        log.debug("entering 'onSubmit' method...");

        boolean isNew = (activities.getIdactivities() == null);
        String success = getSuccessView();
        Locale locale = request.getLocale();

        if (request.getParameter("delete") != null) {
            activitiesManager.remove(activities.getIdactivities());
            saveMessage(request, getText("activities.deleted", locale));
        } else {
            activities = activitiesManager.save(activities);
            String key = (isNew) ? "activities.added" : "activities.updated";
            saveMessage(request, getText(key, locale));

            success = "redirect:ideadisplay?ididea=" + activities.getIdea().getIdidea() + "#businesscanvas";

        }

        return success;
    }
}

src/main/java/com/ubuniworks/webapp/controller/ChannesController.java
package com.ubuniworks.webapp.controller;

import com.ubuniworks.dao.SearchException;
import com.ubuniworks.service.GenericManager;
import com.ubuniworks.model.Channes;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ExtendedModelMap;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping("/channess*")
public class ChannesController {
    private GenericManager<Channes, Integer> channesManager;

    @Autowired
    public void setChannesManager(@Qualifier("channesManager") GenericManager<Channes, Integer> channesManager) {
        this.channesManager = channesManager;
    }

    @RequestMapping(method = RequestMethod.GET)
    public Model handleRequest(@RequestParam(required = false, value = "q") String query)
    throws Exception {
        Model model = new ExtendedModelMap();
        try {
            model.addAttribute(channesManager.search(query, Channes.class));
        } catch (SearchException se) {
            model.addAttribute("searchError", se.getMessage());
            model.addAttribute(channesManager.getAll());
        }
        return model;
    }
}

src/main/webapp/decorators/default.jsp
<!DOCTYPE html>
<%@ include file="/common/taglibs.jsp" %>
<html lang="en">
<head>
    <meta http-equiv="Cache-Control" content="no-store"/>
    <meta http-equiv="Pragma" content="no-cache"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="<c:url value="/images/logo-sm.png"/>"/>
    <title><decorator:title/> | <fmt:message key="webapp.name"/></title>
    <t:assets type="css"/>
    <link href="<c:url value="styles/font-awesome-4.6.2/css/font-awesome.min.css"/>" rel='stylesheet' type='text/css'>
    <link href="<c:url value="styles/sidemenu.css"/>" rel='stylesheet' type='text/css'>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link href="<c:url value="assets/global/plugins/font-awesome/css/font-awesome.min.css"/>" rel="stylesheet" type="text/css" />
        <link href="<c:url value="assets/global/plugins/font-awesome/css/font-awesome.min.css"/>" rel="stylesheet" type="text/css" />
        <link href="<c:url value="assets/global/plugins/simple-line-icons/simple-line-icons.min.css"/>" rel="stylesheet" type="text/css" />
        <link href="<c:url value="assets/global/plugins/bootstrap/css/bootstrap.min.css"/>" rel="stylesheet" type="text/css" />
        <link href="<c:url value="assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css"/>" rel="stylesheet" type="text/css" />
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="<c:url value="assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css"/>" rel="stylesheet" type="text/css" />
        <link href="<c:url value="assets/global/plugins/morris/morris.css"/>" rel="stylesheet" type="text/css" />
        <link href="<c:url value="assets/global/plugins/fullcalendar/fullcalendar.min.css"/>" rel="stylesheet" type="text/css" />
        <link href="<c:url value="assets/global/plugins/jqvmap/jqvmap/jqvmap.css"/>" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="<c:url value="assets/global/css/components.min.css"/>" rel="stylesheet" id="style_components" type="text/css" />
        <link href="<c:url value="assets/global/css/plugins.min.css"/>" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <link href="<c:url value="assets/layouts/layout3/css/layout.min.css"/>" rel="stylesheet" type="text/css" />
        <link href="<c:url value="assets/layouts/layout3/css/themes/default.min.css"/>" rel="stylesheet" type="text/css" id="style_color" />
        <link href="<c:url value="assets/layouts/layout3/css/custom.min.css"/>" rel="stylesheet" type="text/css" />
        <!-- END THEME LAYOUT STYLES -->
        <link rel="shortcut icon" href="favicon.ico" /> </head>
    
    <decorator:head/>
    <t:assets type="js"/>
    <%= (request.getAttribute("scripts") != null) ? request.getAttribute("scripts") : "" %>
</head>
<body<decorator:getProperty property="body.id" writeEntireProperty="true"/><decorator:getProperty property="body.class"
                                                                                                  writeEntireProperty="true"/>>
<c:set var="currentMenu" scope="request"><decorator:getProperty property="meta.menu"/></c:set>

 <!-- BEGIN HEADER -->
        <div class="page-header">
            <!-- BEGIN HEADER TOP -->
            <div class="page-header-top">
                <div class="container">
                    <!-- BEGIN LOGO -->
                    <div class="page-logo">
                        <a href="<c:url value='/'/>">
                            <img src="<c:url value="assets/layouts/layout3/img/logo.png"/>" alt="<fmt:message key="webapp.name"/>" class="logo-default">
                        </a>
                    </div>
                    <!-- END LOGO -->
                    <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                    <a href="javascript:;" class="menu-toggler"></a>
                    <!-- END RESPONSIVE MENU TOGGLER -->
                    <!-- BEGIN TOP LOGIN AREA -->
                   <div class="top-menu">
 <ul class="nav navbar-nav pull-right">
                            <!-- BEGIN NOTIFICATION DROPDOWN -->
                            <li class="dropdown dropdown-extended dropdown-notification dropdown-dark" id="header_notification_bar">
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                    <i class="icon-bell"></i>
                                    <span class="badge badge-default">7</span>
                                </a>
                            
                            </li>
                            <!-- END NOTIFICATION DROPDOWN -->
                            <!-- BEGIN TODO DROPDOWN -->
                            <li class="dropdown dropdown-extended dropdown-tasks dropdown-dark" id="header_task_bar">
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                    <i class="icon-calendar"></i>
                                    <span class="badge badge-default">3</span>
                                </a>
                               
                            </li>
                            <!-- END TODO DROPDOWN -->
                            <li class="droddown dropdown-separator">
                                <span class="separator"></span>
                            </li>
                            <!-- END INBOX DROPDOWN -->
                            <!-- BEGIN USER LOGIN DROPDOWN -->
                            <li class="dropdown dropdown-user dropdown-light">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
                                 <span class="username username-hide-mobile">Welcome ${user.fullName}</span>
                                </a>
                                <ul class="dropdown-menu extended tasks">
                                    <li class="external">
                                       <a href="<c:url value="/profile-overview"/>"><i class="icon-user"></i> Profile Overview</a>
                                    </li>
                                    <li class="external">
                                       <a href="<c:url value="/profile"/>"><i class="icon-settings"></i> Account Setting</a>
                            </li>
                                    <li class="external">
                                       <a href="<c:url value="/userform"/>"><i class="icon-settings"></i> Update your Information</a>
                            </li>
                                    <li class="external"><a href="logout">
                                    <i class="icon-power"></i> Logout
                                </a></li>
                            <!-- END USER LOGIN DROPDOWN -->
                           
                        </ul>    
</div>
                </div>
            </div>
            <!-- END HEADER TOP -->
       
        </div>
<div>
    <%@ include file="/common/messages.jsp" %>
    <div class="row">
        <decorator:body/>

        <c:if test="${currentMenu == 'AdminMenu'}">
            <div class="col-sm-2">
                <menu:useMenuDisplayer name="Velocity" config="navlistMenu.vm" permissions="rolesAdapter">
                    <menu:displayMenu name="AdminMenu"/>
                </menu:useMenuDisplayer>
            </div>
        </c:if>
    </div>
</div>
  <!-- BEGIN INNER FOOTER -->
        <div class="page-footer">
            <div class="container">
            <div class="row"><div class="col-sm-6" >
                <ul class="footer-left">
                <li><a href="#">About Us</a></li> 
                <li><a href="#">Terms of Service</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Contact Us</a></li>               
                </ul>
                </div>
                <div class="col-sm-6">
                <ul class="footer-right">
                <li><a href="#">Help</a></li> 
                <li><a href="#">How it Works</a></li>
                    <li><a href="#">Report a Problem</a></li>
                               
                </ul>
                </div></div>
                <div class="row">
                <div class="col-sm-12"><div class="copy">
                ESN &copy; 2016    
                </div></div>
                </div>
            </div>
        </div>
 <!-- BEGIN CORE PLUGINS -->
        <script src="<c:url value="assets/global/plugins/jquery.min.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/bootstrap/js/bootstrap.min.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/js.cookie.min.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery.blockui.min.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js"/>" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<c:url value="assets/global/plugins/fancybox/source/jquery.fancybox.pack.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/js/vendor/tmpl.min.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/js/vendor/load-image.min.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/js/vendor/canvas-to-blob.min.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/blueimp-gallery/jquery.blueimp-gallery.min.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/js/jquery.iframe-transport.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/js/jquery.fileupload.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/js/jquery.fileupload-process.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/js/jquery.fileupload-image.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/js/jquery.fileupload-audio.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/js/jquery.fileupload-video.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/js/jquery.fileupload-validate.js"/>" type="text/javascript"></script>
        <script src="<c:url value="assets/global/plugins/jquery-file-upload/js/jquery.fileupload-ui.js"/>" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="<c:url value="assets/global/scripts/app.min.js"/>" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
    
        <!-- END PAGE LEVEL SCRIPTS -->
       
</body>
</html>